spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root@123
    url: jdbc:mysql://localhost:3306/recipe_2_plate
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: mysql

