spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root@123
    url: jdbc:mysql://localhost:3306/recipe_2_plate
  jpa:
    show-sql: true
    database: mysql

  flyway:
    user: root
    password: root@123
    url: jdbc:mysql://localhost:3306/recipe_2_plate
    baseline-on-migrate: true

server:
  servlet:
    context-path: "/api"

security.jwt.token.secret-key: qwemqkweqtqkjeqkwehqbgtqkwjeqlkjw


