spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root@123
    url: jdbc:mysql://localhost:3306/recipe_2_plate
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    database: mysql


  main:
    allow-bean-definition-overriding: true
security.jwt.token.secret-key: qwemqkweqtqkjeqkwehqbgtqkwjeqlkjw



graphql:
  altair:
    enabled: true
    mapping: /altair
    subscriptions:
      timeout: 30
      reconnect: false
    static:
      base-path: /
    page-title: Altair
    cdn:
      enabled: false
      version: 4.0.2
    options:
      endpoint-url: /graphql
      subscriptions-endpoint: /subscriptions
      initial-settings:
        theme: dracula


